### ISSUE TITLE
role-has-required-aria-props broken in 6.2.0 (The prop must be a JSXAttribute collected by the AST parser)

### ISSUE THREAD

**Issue by alasdairhurst** [evcohen/eslint-plugin-jsx-a11y#536]
I have added a second comment with a reproducible case.

The following PR was included in the release and looks like the culprit since it's coming from the new isSemanticElement.js file: https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/491/files

This is the error that I'm getting:
```
The prop must be a JSXAttribute collected by the AST parser.
Error: The prop must be a JSXAttribute collected by the AST parser.
    at propName (C:\git\axway-react-ui\node_modules\jsx-ast-utils\lib\propName.js:15:11)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:21:67
    at Array.some (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:20:25
    at Array.every (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:19:68
    at Map.forEach (<anonymous>)
    at isSemanticRoleElement (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:15:35)
    at JSXAttribute (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\rules\role-has-required-aria-props.js:72:49)
    at listeners.(anonymous function).forEach.listener (C:\git\axway-react-ui\node_modules\eslint\lib\util\safe-emitter.js:47:58)
```

After adding the first few logs into the place of the error, jsx-ast-utils is expecting a JSXAttribute, however, it's actually getting a JSXSpreadAttribute

It's the same issue that creeped in with 6.1.0: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/459

```
  if (!prop.type || prop.type !== 'JSXAttribute') {
    console.trace(prop);
    throw new Error('The prop must be a JSXAttribute collected by the AST parser.');
  }
```

```
Trace: Node {
  type: 'JSXSpreadAttribute',
  start: 6725,
  end: 6735,
  loc:
   SourceLocation {
     start: Position { line: 282, column: 2 },
     end: Position { line: 282, column: 12 } },
  range: [ 6725, 6735 ],
  argument:
   Node {
     type: 'Identifier',
     start: 6729,
     end: 6734,
     loc: SourceLocation { start: [Position], end: [Position] },
     range: [ 6729, 6734 ],
     name: 'props' } }
    at propName (C:\git\axway-react-ui\node_modules\jsx-ast-utils\lib\propName.js:14:11)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:21:67
    at Array.some (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:20:25
    at Array.every (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:19:68
    at Map.forEach (<anonymous>)
    at isSemanticRoleElement (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:15:35)
    at JSXAttribute (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\rules\role-has-required-aria-props.js:71:49)
    at listeners.(anonymous function).forEach.listener (C:\git\axway-react-ui\node_modules\eslint\lib\util\safe-emitter.js:47:58)
The prop must be a JSXAttribute collected by the AST parser.
Error: The prop must be a JSXAttribute collected by the AST parser.
    at propName (C:\git\axway-react-ui\node_modules\jsx-ast-utils\lib\propName.js:15:11)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:21:67
    at Array.some (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:20:25
    at Array.every (<anonymous>)
    at C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:19:68
    at Map.forEach (<anonymous>)
    at isSemanticRoleElement (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\util\isSemanticRoleElement.js:15:35)
    at JSXAttribute (C:\git\axway-react-ui\node_modules\eslint-plugin-jsx-a11y\lib\rules\role-has-required-aria-props.js:71:49)
    at listeners.(anonymous function).forEach.listener (C:\git\axway-react-ui\node_modules\eslint\lib\util\safe-emitter.js:47:58)
```

**Comment by jessebeach** [comment]
Fixed in #545 

Bumping the project to v6.2.1 and pushing a release ASAP.

**Comment by jessebeach** [comment]
@alasdairhurst thank you for documenting this issue!

**Comment by jessebeach** [comment]
v6.2.1 released: https://www.npmjs.com/package/eslint-plugin-jsx-a11y
