### ISSUE TITLE
Exception after update to 1.4.0

### ISSUE THREAD

**Issue by SethDavenport** [evcohen/eslint-plugin-jsx-a11y#59]
Since updating from 1.3.0 to 1.4.0, I'm getting the following stack trace when I run `eslint`:

```
> eslint '**/*.js' --ignore-path .eslintignore

Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/sdavenpo/code/my-proj/node_modules/eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props.js:59:54
    at Array.forEach (native)
    at EventEmitter.JSXOpeningElement (/Users/sdavenpo/code/my-proj/node_modules/eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props.js:58:23)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/sdavenpo/code/my-proj/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/sdavenpo/code/my-proj/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/sdavenpo/code/my-proj/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/sdavenpo/code/my-proj/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/Users/sdavenpo/code/my-proj/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

Any ideas? FWIW I'm running nodejs 6.2.1.

**Comment by evcohen** [comment]
Think I may have a fix for this given limited info. There are multiple different types of attributes, but this is assuming that the name property is only one of them. Your code may be using a component with a different naming convention, so I am going to fix in next couple mins and then we can re-test. Thanks for reporting!

**Comment by evcohen** [comment]
My hypothesis was wrong, hmm. Is there any other info you can dig up about the context of the error?

**Comment by evcohen** [comment]
Ah it could be failing on a spread props. Are you using that in the code? 

```jsx
<div {...props} />
```

**Comment by evcohen** [comment]
[v1.4.1](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/1.4.1) published, can you try running again and see if it's fixed? Thanks!

**Comment by evcohen** [comment]
@SethDavenport can we close?
